server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    com.pm: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
